a=("rose","lily","sunflower","lotus","jasmine","daisy")
print(a)
print(type(a))
print(len(a))
b=tuple((3,4,5,6,7,8))
print(b)
print(a[2])
print(a[-4])
print(a[3:5])
print(a[-6:-4])
print("rose" in a)
print("rose" not in a)
print("tulip" in a)
print("tulip" not in a)
x=list(a)
print(x)
x.append("hibscus")
print(x)
a=tuple(x)
print(a)
x.remove("lotus")
print(x)
for i in a:
    print(i)
z=a+b
print(z)
print(a*2)
print(a.count("rose"))
