x=("football","cricket","basketball","boxing","chess")
print(x)
print(type(x))
print(len(x))
print(x[3])
print(x[-3])
print(x[2:4])
print(x[-4:-1])
print("volleyball" in x)
print("volleyball" not in x)
print("football" in x)
print("football" not in x)
a=list(x)
print(a)
a.append("swimming")
print(a)
x=tuple(a)
print(x)
a.remove("cricket")
print(a)
x=tuple(a)
print(x)
for i in x:
    print(i)
y=tuple((5,3,7,2,1) ) 
print(y)
b=x+y
print(b) 
print(x*2)
k=y.count(5)
print(k)
