x=("car","bike","bus","cycle","train")
print(x)
print(type(x))
print(len(x))
y=tuple((1,2,3,4,5))
print(y)
z=("monday",)
print(z)
print(type(z))
print(x[4])
print(x[-3])
print(x[-4:-2])
print(x[3:5])
print(x[2:])
print(x[:5])
print("bike" in x)
print("bike" not in x)
print("scooty"in x)
print("scooty" not in x)
a=list(x)
print(a)
a.append("flight")
print(a)
x=tuple(a)
print(x)
a.remove("bike")
print(a)
x=tuple(a)
print(a)
for i in x:
    print(i)
b=x+y
print(b)
print(x*2)
print(y.count(3))